/**
 * 客户钻取弹窗模拟数据
 * 从 salesAnalysis.ts 拆分，减少主文件行数
 */

import type { DrilldownRiskGroup } from '@/types/sales-analysis';

export const CUSTOMER_DRILLDOWN: Record<string, DrilldownRiskGroup> = {
  red: {
    title: '高风险客户名单',
    desc: '先处理回款异常与停单风险，再逐个查看客户详情与建议动作。',
    tagText: '立即处理',
    tagColor: 'red',
    countText: '共 28 位客户',
    filterNote: '优先看逾期和长时间未下单客户，方便管理层先抓最急的问题。',
    myView: {
      title: '我的高风险 6',
      note: '优先关注回款异常与停单风险，先稳住核心客户，再决定是否升级主管协同。',
      desc: '先看我名下需要优先处理的高风险客户，再判断是否需要升级协同动作。',
      filterNote: '先按我的客户里的风险原因筛选，再逐个确认催款和保客动作。',
      focusLabel: '今日优先处理',
      focusStatus: '待跟进',
      focusName: '华东旗舰店',
      focusNote: '先催回款，再确认补单节奏，避免从回款风险演变为持续停单。',
    },
    filters: [
      { key: 'all', label: '全部' },
      { key: 'receipt', label: '回款异常' },
      { key: 'sleep', label: '30天未下单' },
    ],
    customers: [
      {
        id: 'red-hd-flagship',
        name: '华东旗舰店',
        tags: [{ text: '回款异常', color: 'red' }, { text: 'A类客户', color: 'blue' }],
        summary: '未回款金额较高，且近 34 天未补单，已经影响本月回款节奏。',
        owner: '张晨',
        order: '最近下单 34 天前',
        followUp: '最近跟进 12 天前',
        action: '建议先由销售主管介入催回款，并确认是否需要临时停单。',
        filters: ['receipt', 'sleep'],
        isMine: true,
        detail: {
          subtitle: '核心客户，但近期回款与续单同步失速，需要优先保客户、控风险。',
          metrics: [
            { label: '未回款金额', value: '¥48,000' },
            { label: '逾期天数', value: '36 天' },
            { label: '近30天订单额', value: '¥12,600' },
          ],
          reasons: ['逾期超 30 天', '34 天未补单', '重点客户回款降速'],
          trend: [92, 84, 68, 44],
          payment: '最近一笔回款为 3 月 2 日，金额 ¥12,000，当前仍有 4 笔账期未结清。',
          followups: [
            '4 月 1 日电话催办，客户反馈资金周转紧张。',
            '3 月 27 日上门拜访，提出先回 30% 再补货。',
            '3 月 18 日发送对账单，尚未收到完整确认。',
          ],
          coverage: [{ label: '饮料', value: 86 }, { label: '零食', value: 52 }, { label: '日配', value: 28 }],
          actions: ['安排主管陪访', '设置回款承诺节点', '恢复重点 SKU 补货节奏'],
        },
      },
      {
        id: 'red-shengan',
        name: '盛安商贸',
        tags: [{ text: '回款异常', color: 'red' }, { text: 'B类客户', color: 'green' }],
        summary: '账期连续两个月拉长，回款金额低于历史均值，风险正在放大。',
        owner: '李洋',
        order: '最近下单 9 天前',
        followUp: '最近跟进 4 天前',
        action: '建议将账期审批收紧，并按周跟踪剩余应收。',
        filters: ['receipt'],
        isMine: false,
        detail: {
          subtitle: '近期仍有订单，但回款节奏明显变慢，需防止风险从黄转红。',
          metrics: [
            { label: '未回款金额', value: '¥31,500' },
            { label: '逾期天数', value: '33 天' },
            { label: '近30天订单额', value: '¥41,000' },
          ],
          reasons: ['逾期超 30 天', '连续 2 周回款不足计划值', '账期审批放宽'],
          trend: [76, 74, 71, 62],
          payment: '客户近两次仅支付小额尾款，主单款项仍未按承诺到账。',
          followups: [
            '4 月 6 日业务员上门沟通，客户希望延长账期 10 天。',
            '4 月 3 日财务电话提醒，客户承诺本周补回款。',
            '3 月 29 日发送账龄预警给销售主管。',
          ],
          coverage: [{ label: '饮料', value: 72 }, { label: '零食', value: 63 }, { label: '日配', value: 35 }],
          actions: ['冻结新增授信', '设定每周回款目标', '复核账期政策'],
        },
      },
      {
        id: 'red-yuantuo',
        name: '远拓连锁',
        tags: [{ text: '30天未下单', color: 'orange' }, { text: 'B类客户', color: 'green' }],
        summary: '该客户过去贡献稳定，但近期连续停单，存在被竞品替代迹象。',
        owner: '周凯',
        order: '最近下单 41 天前',
        followUp: '最近跟进 19 天前',
        action: '建议尽快恢复拜访，确认是否因价格或库存问题停单。',
        filters: ['sleep'],
        isMine: false,
        detail: {
          subtitle: '停单超过 40 天，且业务员跟进频率不足，需先判断能否挽回。',
          metrics: [
            { label: '停单时长', value: '41 天' },
            { label: '历史月均订单', value: '¥58,000' },
            { label: '上次回款', value: '¥19,800' },
          ],
          reasons: ['超过 30 天未下单', '重点门店被竞品切入', '近 2 周未拜访'],
          trend: [88, 76, 38, 14],
          payment: '当前无明显逾期，但停单导致后续账款回笼也同步下滑。',
          followups: [
            '3 月 30 日客户反馈竞品促销力度更大。',
            '3 月 21 日业务员电话沟通，客户表示等新活动方案。',
            '3 月 10 日最后一次补货后未再产生订单。',
          ],
          coverage: [{ label: '饮料', value: 68 }, { label: '零食', value: 47 }, { label: '日配', value: 21 }],
          actions: ['恢复周拜访', '补价格与促销方案', '评估重点门店抢回计划'],
        },
      },
    ],
  },
  yellow: {
    title: '预警客户名单',
    desc: '重点关注订单下滑与跟进不足客户，避免风险继续恶化为高风险。',
    tagText: '尽快跟进',
    tagColor: 'orange',
    countText: '共 46 位客户',
    filterNote: '先判断是需求下滑还是跟进节奏不足，再分配销售动作。',
    myView: {
      title: '我的预警 9',
      note: '订单下滑和跟进不足并存，适合先补拜访和门店动作，避免继续转红。',
      desc: '先查看我名下需要尽快跟进的预警客户，再决定是否补充主管支持。',
      filterNote: '先定位是订单下滑还是跟进不足，再安排我的客户优先动作。',
      focusLabel: '我先跟进',
      focusStatus: '尽快处理',
      focusName: '城市便利店A03',
      focusNote: '先排查主力 SKU 缺货，再补拜访和陈列动作，避免订单继续走弱。',
    },
    filters: [
      { key: 'all', label: '全部' },
      { key: 'drop', label: '订单下滑' },
      { key: 'visit', label: '跟进不足' },
    ],
    customers: [
      {
        id: 'yellow-bianli-a03',
        name: '城市便利店A03',
        tags: [{ text: '订单下滑', color: 'orange' }, { text: '便利店', color: 'blue' }],
        summary: '近 30 天订单额较上周期下降 38%，下单频次也同步减少。',
        owner: '张晨',
        order: '最近下单 8 天前',
        followUp: '最近跟进 6 天前',
        action: '建议先排查主力 SKU 缺货，再确认陈列与竞品活动情况。',
        filters: ['drop'],
        isMine: true,
        detail: {
          subtitle: '属于下滑明显但仍有成交的客户，及时干预可避免转为高风险。',
          metrics: [{ label: '订单跌幅', value: '-38%' }, { label: '近30天订单额', value: '¥15,400' }, { label: '下单次数', value: '4 次' }],
          reasons: ['订单额下降超 30%', '下单频次从 7 次降到 4 次', '主力 SKU 陈列缩减'],
          trend: [84, 72, 58, 46],
          payment: '回款正常，但客单价与下单频次均在下滑。',
          followups: ['4 月 5 日门店反馈缺少促销物料支持。', '4 月 1 日盘点发现两支主推 SKU 缺货。', '3 月 23 日业务员拍照回传，竞品端架位置增加。'],
          coverage: [{ label: '饮料', value: 78 }, { label: '零食', value: 44 }, { label: '日配', value: 18 }],
          actions: ['补货主推 SKU', '增加门店陈列', '复盘竞品活动强度'],
        },
      },
      {
        id: 'yellow-jinhe',
        name: '金禾商超',
        tags: [{ text: '跟进不足', color: 'orange' }, { text: '商超', color: 'green' }],
        summary: 'A/B 类客户已超过 11 天未拜访，近期仅保留被动成交，主动维护不足。',
        owner: '李洋',
        order: '最近下单 6 天前',
        followUp: '最近跟进 11 天前',
        action: '建议恢复固定拜访频率，并检查陈列和档期计划是否缺失。',
        filters: ['visit'],
        isMine: false,
        detail: {
          subtitle: '当前还没明显流失，但维护动作偏弱，适合尽快恢复节奏。',
          metrics: [{ label: '未拜访时长', value: '11 天' }, { label: '本月订单额', value: '¥23,600' }, { label: '目标完成率', value: '76%' }],
          reasons: ['A/B 类客户超 9 天未拜访', '本月陈列提报为空', '客户反馈缺少活动建议'],
          trend: [68, 66, 64, 60],
          payment: '回款正常，主要风险来自维护不及时导致订单逐步走弱。',
          followups: ['4 月 4 日客户要求提供下周促销建议。', '3 月 29 日业务员电话联系，无实地拜访记录。', '3 月 21 日上次到店后未再更新跟进内容。'],
          coverage: [{ label: '饮料', value: 65 }, { label: '零食', value: 58 }, { label: '日配', value: 32 }],
          actions: ['恢复每周拜访', '补充促销建议', '更新门店陈列计划'],
        },
      },
      {
        id: 'yellow-xinyu',
        name: '新裕餐饮',
        tags: [{ text: '订单下滑', color: 'orange' }, { text: '跟进不足', color: 'red' }],
        summary: '订单和跟进同步走弱，是典型需要尽快介入的黄卡客户。',
        owner: '周凯',
        order: '最近下单 14 天前',
        followUp: '最近跟进 16 天前',
        action: '建议主管陪访，重新确认需求和菜单变化后再给组合方案。',
        filters: ['drop', 'visit'],
        isMine: false,
        detail: {
          subtitle: '既有销量下滑，也有跟进缺口，若继续放任容易转红。',
          metrics: [{ label: '订单跌幅', value: '-34%' }, { label: '未拜访时长', value: '16 天' }, { label: '本月订单额', value: '¥9,800' }],
          reasons: ['订单额下降超 30%', '超过 15 天未跟进', '菜单更新后未跟推新品'],
          trend: [72, 56, 42, 30],
          payment: '目前回款未异常，但订单萎缩使后续价值下降明显。',
          followups: ['4 月 2 日客户更换菜单结构，原有品项需求减少。', '3 月 25 日业务员未按计划完成上门拜访。', '3 月 17 日客户提出想看更适配餐饮场景的组合方案。'],
          coverage: [{ label: '饮料', value: 58 }, { label: '零食', value: 22 }, { label: '日配', value: 40 }],
          actions: ['主管陪访复盘', '补组合方案', '恢复周节奏跟进'],
        },
      },
    ],
  },
  blue: {
    title: '扩品机会名单',
    desc: '挑出品类覆盖偏低但有增长潜力的客户，辅助制定增购和覆盖策略。',
    tagText: '增长机会',
    tagColor: 'blue',
    countText: '共 33 位客户',
    filterNote: '优先看品类覆盖低于同类均值的客户，再判断哪些更适合先做扩品。',
    myView: {
      title: '我的机会 7',
      note: '扩品机会主要集中在便利店与商超，可结合新品试销和陈列优化优先推进。',
      desc: '先看我名下更值得优先推进的扩品客户，再决定是否扩大到整体机会池。',
      filterNote: '先按品类过少或高潜机会筛选，再安排我的客户试销与扩品动作。',
      focusLabel: '我先推进',
      focusStatus: '可推进',
      focusName: '城市便利店A03',
      focusNote: '适合先从高周转新品试销切入，再逐步扩大品类覆盖和陈列位置。',
    },
    filters: [
      { key: 'all', label: '全部' },
      { key: 'few', label: '品类过少' },
      { key: 'potential', label: '扩品潜力高' },
    ],
    customers: [
      {
        id: 'blue-a03',
        name: '城市便利店A03',
        tags: [{ text: '品类过少', color: 'blue' }, { text: '高潜力', color: 'green' }],
        summary: '同类型客户平均采购 9 个品类，该客户仅采购 4 个，仍有较大扩品空间。',
        owner: '张晨',
        order: '最近下单 5 天前',
        followUp: '最近跟进 3 天前',
        action: '建议从高周转小包装和冷柜新品先切入，降低试错成本。',
        filters: ['few', 'potential'],
        isMine: true,
        detail: {
          subtitle: '基础销量稳定，扩品接受度较高，适合作为本月增长样板客户。',
          metrics: [{ label: '当前品类数', value: '4 类' }, { label: '同类平均', value: '9 类' }, { label: '扩品空间', value: '+5 类' }],
          reasons: ['品类数低于同类均值', '高频门店人流稳定', '冷柜陈列仍有空位'],
          trend: [46, 52, 58, 66],
          payment: '回款正常，历史订单稳定，适合作为扩品试点客户。',
          followups: ['4 月 7 日客户愿意尝试 2 个新品试销。', '4 月 3 日门店反馈冷藏饮品需求在上升。', '3 月 28 日业务员确认可增加一组端架陈列。'],
          coverage: [{ label: '饮料', value: 82 }, { label: '零食', value: 24 }, { label: '日配', value: 10 }],
          actions: ['优先推 2 个新品', '追加端架陈列', '两周复盘试销结果'],
        },
      },
      {
        id: 'blue-yuelai',
        name: '悦来网吧',
        tags: [{ text: '品类过少', color: 'blue' }, { text: '网吧', color: 'orange' }],
        summary: '当前只采购饮料类产品，夜宵零食与套餐类商品几乎没有覆盖。',
        owner: '王宁',
        order: '最近下单 12 天前',
        followUp: '最近跟进 5 天前',
        action: '建议从高频零食组合切入，提升连带销售和客单价。',
        filters: ['few'],
        isMine: false,
        detail: {
          subtitle: '该客户场景清晰，适合围绕夜间消费场景做横向扩品。',
          metrics: [{ label: '当前品类数', value: '2 类' }, { label: '同类平均', value: '6 类' }, { label: '潜在提升', value: '¥6,000/月' }],
          reasons: ['只覆盖单一主品类', '夜间客流稳定', '收银台周边缺少冲动型商品'],
          trend: [40, 42, 44, 48],
          payment: '回款稳定，订单规模不大但具备长期提升空间。',
          followups: ['4 月 6 日店长反馈愿意尝试小包装零食组合。', '4 月 1 日现场拍照显示收银台陈列空白较多。', '3 月 22 日客户表示对套装促销感兴趣。'],
          coverage: [{ label: '饮料', value: 76 }, { label: '零食', value: 12 }, { label: '日配', value: 6 }],
          actions: ['上新零食组合', '补收银台陈列', '设计夜间套餐'],
        },
      },
      {
        id: 'blue-minsheng',
        name: '民生商超',
        tags: [{ text: '扩品潜力高', color: 'green' }, { text: '商超', color: 'blue' }],
        summary: '当前已有稳定销量，若补齐日配与家庭装品类，预计可带来明显增量。',
        owner: '李洋',
        order: '最近下单 4 天前',
        followUp: '最近跟进 2 天前',
        action: '建议结合节日档期打包扩品，提高一次性进货意愿。',
        filters: ['potential'],
        isMine: false,
        detail: {
          subtitle: '客户基础盘稳、沟通顺畅，适合做阶段性扩品项目。',
          metrics: [{ label: '当前品类数', value: '6 类' }, { label: '同类平均', value: '8 类' }, { label: '预计增量', value: '¥8,500/月' }],
          reasons: ['日配与家庭装缺口明显', '促销档期即将开始', '客户对套餐陈列接受度高'],
          trend: [54, 58, 64, 72],
          payment: '回款表现良好，具备承接扩品后的稳定补货能力。',
          followups: ['4 月 8 日客户确认愿意测试家庭装陈列。', '4 月 2 日门店给出两个堆头位置可供申请。', '3 月 26 日业务员已提交节日档期活动方案。'],
          coverage: [{ label: '饮料', value: 74 }, { label: '零食', value: 61 }, { label: '日配', value: 26 }],
          actions: ['节日档期扩品', '增加堆头陈列', '同步套餐物料'],
        },
      },
    ],
  },
};
