-- 生产环境一次性迁移历史预填脚本
-- 用途：将 001-149 号迁移标记为已执行，使下次部署时自动迁移系统执行 150+ 号迁移（当前新增：150-159）
-- 执行方式：SSH 到生产服务器，进入 psql 后执行本文件
-- 注意：使用 ON CONFLICT DO NOTHING 确保幂等，可安全重复执行

-- 确保 migrations_history 表存在
CREATE TABLE IF NOT EXISTS migrations_history (
  id SERIAL PRIMARY KEY,
  filename VARCHAR(255) NOT NULL UNIQUE,
  executed_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO migrations_history (filename) VALUES
  ('001_auth_schema.sql'),
  ('002_performance_indexes.sql'),
  ('002_strategic_products.sql'),
  ('003_expiring_return.sql'),
  ('007_add_days_to_expire_at_return.sql'),
  ('008_add_order_no.sql'),
  ('009_procurement_monthly_archive.sql'),
  ('010_return_penalty.sql'),
  ('011_role_adjustments.sql'),
  ('013_warehouse_evidence.sql'),
  ('014_warehouse_evidence_multi.sql'),
  ('020_drop_ar_tables.sql'),
  ('022_ar_collection.sql'),
  ('023_ar_warning_reminders.sql'),
  ('024_add_marketer_role.sql'),
  ('025_add_bill_no_to_collection_details.sql'),
  ('026_convert_timezone_to_beijing.sql'),
  ('027_merge_collection_tasks.sql'),
  ('028_add_warehouse_roles.sql'),
  ('029_dingtalk_notification_logs.sql'),
  ('030_oa_approval.sql'),
  ('031_dingtalk_sync_schema.sql'),
  ('032_fixed_asset_management.sql'),
  ('033_asset_fine_grained_permissions.sql'),
  ('034_oa_approval_role_permissions.sql'),
  ('035_oa_approval_erp_meta.sql'),
  ('036_drop_asset_applications.sql'),
  ('037_fix_duplicate_collection_tasks.sql'),
  ('038_add_strategic_export_permission.sql'),
  ('039_remove_orphaned_permissions.sql'),
  ('040_ar_assessment.sql'),
  ('041_ar_assessment_handle_status.sql'),
  ('042_restore_ar_collection_verify_permission.sql'),
  ('043_add_general_manager_role.sql'),
  ('044_add_credit_permissions.sql'),
  ('045_add_customer_credit_form_type.sql'),
  ('046_update_customer_credit_license_optional.sql'),
  ('047_add_oa_approval_read_for_marketer.sql'),
  ('048_add_customer_credit_auto_node.sql'),
  ('049_update_customer_credit_workflow_tiered.sql'),
  ('050_add_processing_erp_failed_status.sql'),
  ('051_ar_collection_entry_rules.sql'),
  ('052_ar_hoard_excluded_status.sql'),
  ('053_oa_dingtalk_integration.sql'),
  ('054_ar_actions_attachment_url.sql'),
  ('055_add_user_switch_permission.sql'),
  ('056_ar_collection_rollback_support.sql'),
  ('057_unified_assessment.sql'),
  ('058_assessment_appeal_form_type.sql'),
  ('059_credit_license_deferred_upload.sql'),
  ('060_add_procurement_archive_permission.sql'),
  ('061_return_order_dedup_constraint.sql'),
  ('062_unify_marketing_manager_role.sql'),
  ('063_ar_hold_time_limit.sql'),
  ('064_drop_urgency_column.sql'),
  ('065_simplify_customer_credit_workflow.sql'),
  ('066_assessment_appeal_source_fields.sql'),
  ('067_update_assessment_appeal_workflow.sql'),
  ('068_add_approval_current_node_index.sql'),
  ('069_add_pending_stuck_index.sql'),
  ('070_erp_inventory_snapshots.sql'),
  ('071_customer_modify_form_type.sql'),
  ('073_customer_modify_state_options.sql'),
  ('074_customer_modify_diff_fields.sql'),
  ('075_customer_modify_photo_diff.sql'),
  ('076_customer_credit_settlement_details.sql'),
  ('077_rename_oa_permissions.sql'),
  ('078_oa_todo_task_mapping.sql'),
  ('079_oa_process_template_mapping.sql'),
  ('080_oa_process_task_mapping.sql'),
  ('081_oa_process_instance_mapping.sql'),
  ('082_customer_credit_customer_namefield.sql'),
  ('083_drop_deprecated_oa_tables.sql'),
  ('084_token_management.sql'),
  ('085_ar_collection_oa_integration.sql'),
  ('086_simplify_approval_titles.sql'),
  ('087_fix_submit_action_node_order.sql'),
  ('088_fix_ar_collection_instances.sql'),
  ('089_ar_collection_schema_v2.sql'),
  ('090_deprecate_ar_collection_legacy_permissions.sql'),
  ('091_cleanup_dead_ar_tables.sql'),
  ('092_org_structure_schema.sql'),
  ('093_org_structure_permissions.sql'),
  ('094_oa_node_timeout.sql'),
  ('095_fix_escalate_auto_node_data.sql'),
  ('096_fix_unassigned_collection_nodes.sql'),
  ('097_backfill_collection_result_comments.sql'),
  ('098_fix_premature_auto_nodes.sql'),
  ('098_rollback.sql'),
  ('099_oa_multi_approver.sql'),
  ('100_oa_async_tasks.sql'),
  ('101_oa_workflow_handover.sql'),
  ('102_handover_audit_enhancement.sql'),
  ('103_ar_hold_meta.sql'),
  ('104_add_verify_status_column.sql'),
  ('105_procurement_order_form_type.sql'),
  ('106_oa_form_level_permissions.sql'),
  ('107_oa_form_data_permissions.sql'),
  ('108_role_unification.sql'),
  ('109_oa_node_type_simplification.sql'),
  ('110_deprecate_form_schema.sql'),
  ('111_procurement_payment_restructure.sql'),
  ('112_deprecate_workflow_def.sql'),
  ('113_oa_field_permissions.sql'),
  ('114_cc_node_type.sql'),
  ('115_inflight_inputschema_cleanup.sql'),
  ('116_ar_collection_send_back_migration.sql'),
  ('117_ar_collection_condition_migration.sql'),
  ('118_fix_ar_collection_auto_node_failure.sql'),
  ('119_fix_ar_collection_node_status.sql'),
  ('120_on_demand_node_creation.sql'),
  ('121_node_multi_round.sql'),
  ('122_add_round_to_actions.sql'),
  ('123_fix_orphaned_ar_instances.sql'),
  ('124_user_bank_accounts.sql'),
  ('125_logistics_fee_form_type.sql'),
  ('126_field_permissions_full_migration.sql'),
  ('127_auto_node_restructure.sql'),
  ('128_purchase_payment_form_type.sql'),
  ('129_purchase_payment_field_permissions.sql'),
  ('130_customer_reconciliation_form_type.sql'),
  ('131_customer_reconciliation_field_permissions.sql'),
  ('132_modal_select_details_migration.sql'),
  ('135_view_permissions.sql'),
  ('136_remove_reconciliation_summary_fields.sql'),
  ('137_reconciliation_backfill_fields_permissions.sql'),
  ('138_user_signatures.sql'),
  ('139_action_attachments.sql'),
  ('140_reconciliation_receipt_field_permissions.sql'),
  ('141_oa_form_user_permissions.sql'),
  ('142_procurement_order_bank_account_field_permissions.sql'),
  ('143_merge_action_comments.sql'),
  ('144_action_attachments_default.sql'),
  ('145_reconciliation_receipt_view_permissions.sql'),
  ('146_promotion_activity_form_types.sql'),
  ('147_promotion_form_types_offline_rename.sql'),
  ('148_combined_must_select_visible_when.sql'),
  ('149_target_management_permissions.sql')
ON CONFLICT (filename) DO NOTHING;

-- 验证：查看已记录的迁移数量
SELECT COUNT(*) AS total_recorded FROM migrations_history;
-- 验证：查看待执行的迁移（应为 150-153）
SELECT filename FROM migrations_history ORDER BY filename DESC LIMIT 5;
