/**
 * 销售分析模块模拟数据 - 统一导出
 */
export { OVERVIEW_KPIS } from './overview';
export { RISK_CATEGORIES } from './riskDiscovery';
export { TARGET_OVERVIEW, MARKETER_RANKINGS } from './targetTracking';
export {
  CUSTOMER_METRICS,
  CUSTOMER_QUADRANT_CONFIG,
  CUSTOMER_QUADRANT_STATS,
  TOP_CUSTOMERS,
  CHANNEL_DISTRIBUTION,
  DISTRICT_DISTRIBUTION,
  CUSTOMER_CONCENTRATION,
  CUSTOMER_STRUCTURE_DATA,
  CATEGORY_PENETRATION,
  CUSTOMER_DETAILS,
} from './customerAnalysis';
export {
  PRODUCT_METRICS,
  PRODUCT_QUADRANT_CONFIG,
  PRODUCT_QUADRANT_STATS,
  CATEGORY_SALES,
  TOP_PRODUCTS,
  INVENTORY_HEALTH,
  PRODUCT_DETAILS,
} from './productAnalysis';
